### ISSUE TITLE
Bump SVD submodule and regenerate PACs

### ISSUE THREAD

**Issue by tmplt** [atsams-rs/atsamx7x-rust#17]
This issue originates from https://github.com/posborne/cmsis-svd/issues/153.

> After a chat with Microchip it was pointed out that http://packs.download.atmel.com/ is outdated. The up-to-date pack repository is https://packs.download.microchip.com/, where much more recent SVD files for the SAM{E,V,S}7X chips can be found: the latest version for the SAME70 is 4.8.125 (from 2022), versus 2.4.166 (from 2019) mirrored in this repo.
>
>An SVD issue regarding USART-SPI clock sources has also been filed recently; a bug-fix release is expected soon.

## Work items:
- [x] PR new SVDs to [cmsis-svd](https://github.com/posborne/cmsis-svd)
- [x] Update PAC crates code
- [x] Update all references about sources of SVDs used to generate PACs
- [x] Adjust HAL to new PACs changes
- [ ] Publish PAC crates

**Comment by michalfita** [comment]
I'm still waiting for the merge of the PR in the upstream 😞
